# Sample:
# [[plugins]]
# repository =

# Completion
[[plugins]]
repository = 'Shougo/neocomplete.vim'
insert = 1

[[plugins]]
repository = 'Shougo/neosnippet.vim'
insert = 1

[[plugins]]
repository = 'tacahilo/neosnippet-snippets'
depends = ['glidenote/serverspec-snippets', 'tacahilo/itamae-snippets']
insert = 1
filetypes = 'snippet'

[[plugins]]
repository = 'kana/vim-smartinput'
depends = 'cohama/vim-smartinput-endwise'
insert = 1

[[plugins]]
repository = 'cohama/vim-smartinput-endwise'
insert = 1

[[plugins]]
repository = 'AndrewRadev/switch.vim'
commands = 'Switch'

# Syntax
[[plugins]]
repository = 'osyo-manga/vim-watchdogs'
depends = ['osyo-manga/shabadou.vim', 'cohama/vim-hier']
filetypes = 'all'

[[plugins]]
repository = 'evanmiller/nginx-vim-syntax'
filetypes = 'nginx'

[[plugins]]
repository ='cespare/vim-toml'
filetypes = 'toml'

# Markdown or texts
[[plugins]]
repository = 'gist:tacahilo/fda08ddb08cdd90c40f4'
name = 'markdown.vim'
script_type = 'syntax'
filetypes = ['markdown', 'md']

[[plugins]]
repository = 'kannokanno/previm'
filetypes = ['markdown', 'md', 'rst']
depends = 'tyru/open-browser.vim'

[[plugins]]
repository = 'open-browser.vim'
filetypes = ['markdown', 'md', 'rst']
mappings = '<Plug>'
functions = 'openbrowser#open'

[[plugins]]
repository = 'glidenote/memolist.vim'
commands = ['MemoNew', 'MemoList', 'MemoGrep']

# Languages
[[plugins]]
repository = 'rodjek/vim-puppet'
filetypes = 'puppet'

[[plugins]]
repository = 'mattn/emmet-vim'
filetypes = 'html'

[[plugins]]
repository = 'nvie/vim-flake8'
filetypes = 'python'
#
[[plugins]]
repository = 'vim-ruby/vim-ruby'
filetypes = ['ruby', 'eruby']

[[plugins]]
repository = 'vim-perl/vim-perl'
filetypes = 'perl'

# Development
[[plugins]]
repository = 'thinca/vim-quickrun'
commands = 'Quickrun'
mappings = '<Plug>'

## Operators
[[plugins]]
repository = 'kana/vim-operator-user'
functions = 'operator#user#define'

[[plugins]]
repository = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
mappings = [['nx', '<Plug>']]

[[plugins]]
repository = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
mappings = '<Plug>'

# Text objects (textobj)
[[plugins]]
repository = 'kana/vim-textobj-user'

[[plugins]]
repository = 'rhysd/vim-textobj-anyblock'
depends = 'vim-textobj-user'
mappings = [['ox', '<Plug>']]

[[plugins]]
repository = 'thinca/vim-textobj-between'
depends = 'vim-textobj-user'
mappings = [['ox', '<Plug>']]

## GitHub
[[plugins]]
repository = 'lambdalisue/vim-gista'
mappings = '<Plug>(gista-'
commands = 'Gista'
