# Sample:
# [[plugins]]
# repository =

[[plugins]]
repository = 'Shougo/vimproc.vim'

  [plugins.build]
  mac = 'make -f make_mac.mak'
  linux = 'make'
  unix = 'gmake'

# Autocomplete and Snippets
[[plugins]]
repository = 'Shougo/neocomplete.vim'
insert = 1

[[plugins]]
repository = 'Shougo/neosnippet'
insert = 1

[[plugins]]
repository = 'tacahilo/neosnippet-snippets'
depends = ['glidenote/serverspec-snippets', 'tacahilo/itamae-snippets']
insert = 1
filetypes = 'snippet'

# Syntax
[[plugins]]
repository = 'scrooloose/syntastic'

[[plugins]]
repository = 'evanmiller/nginx-vim-syntax'

[[plugins]]
repository = 'ekalinin/Dockerfile.vim'

[[plugins]]
repository ='cespare/vim-toml'
filetypes = 'toml'

