# Sample:
# [[plugins]]
# repository =

[[plugins]]
repository = 'Shougo/vimproc.vim'

  [plugins.build]
  mac = 'make -f make_mac.mak'
  linux = 'make'
  unix = 'gmake'

# Filer
[[plugins]]
repository = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repository = 'justinmk/vim-dirvish'

# Productivities
[[plugins]]
repository = 'Lokaltog/vim-easymotion'

[[plugins]]
repository = '907th/vim-auto-save'

[[plugins]]
repository = 'AndrewRadev/switch.vim'

[[plugins]]
repository = 'bronson/vim-trailing-whitespace'

[[plugins]]
repository = 'tomtom/tcomment_vim'

[[plugins]]
repository = 'kana/vim-smartinput'
depends = 'cohama/vim-smartinput-endwise'

[[plugins]]
repository = 'junegunn/vim-easy-align'

[[plugins]]
repository = 'autofmt'

[[plugins]]
repository = 'tpope/vim-fugitive'

## Display
[[plugins]]
repository = 'itchyny/lightline.vim'

[[plugins]]
repository = 'w0ng/vim-hybrid'

[[plugins]]
repository = 'Yggdroot/indentLine'

## Text objects (textobj)
[[plugins]]
repository = 'kana/vim-textobj-user'

[[plugins]]
repository = 'rhysd/vim-textobj-anyblock'

[[plugins]]
repository = 'thinca/vim-textobj-between'

[[plugins]]
repository = 'osyo-manga/vim-textobj-multiblock'

# Memo
[[plugins]]
repository = 'glidenote/memolist.vim'

[[plugins]]
repository = 'vimwiki'
