# Sample:
# [[plugins]]
# repository =

# Filer
[[plugins]]
repository = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repository = 'justinmk/vim-dirvish'

# Syntax
[[plugins]]
repository = 'bronson/vim-trailing-whitespace'

[[plugins]]
repository = 'tomtom/tcomment_vim'

[[plugins]]
repository = 'junegunn/vim-easy-align'

# Cursor
[[plugins]]
repository = 'Lokaltog/vim-easymotion'

# Productivity
[[plugins]]
repository = '907th/vim-auto-save'

# Display
[[plugins]]
repository = 'itchyny/lightline.vim'

[[plugins]]
repository = 'w0ng/vim-hybrid'

[[plugins]]
repository = 'Yggdroot/indentLine'
