# Sample:
# [[plugins]]
# repository =

[[plugins]]
repository = 'Shougo/vimproc.vim'

  [plugins.build]
  mac = 'make -f make_mac.mak'
  linux = 'make'
  unix = 'gmake'

# Autocomplete and Snippets
[[plugins]]
repository = 'Shougo/neocomplete.vim'
insert = 1

[[plugins]]
repository = 'Shougo/neosnippet'
insert = 1

[[plugins]]
repository = 'tacahilo/neosnippet-snippets'
depends = ['glidenote/serverspec-snippets', 'tacahilo/itamae-snippets']
insert = 1
filetypes = 'snippet'

# Syntax
[[plugins]]
repository = 'scrooloose/syntastic'

[[plugins]]
repository = 'evanmiller/nginx-vim-syntax'

[[plugins]]
repository = 'ekalinin/Dockerfile.vim'

[[plugins]]
repository ='cespare/vim-toml'
filetypes = 'toml'

# Markdown or texts
[[plugins]]
repository = 'gist:tacahilo/fda08ddb08cdd90c40f4'
name = 'markdown.vim'
script_type = 'syntax'

[[plugins]]
repository = 'kannokanno/previm'
filetypes = ['markdown', 'md', 'rst']
depends = 'tyru/open-browser.vim'

[[plugins]]
repository = 'open-browser.vim'
filetypes = ['markdown', 'md', 'rst']
mappings = '<Plug>'
functions = 'openbrowser#open'

# Languages
[[plugins]]
repository = 'rodjek/vim-puppet'
filetypes = 'puppet'

[[plugins]]
repository = 'mattn/emmet-vim'
filetypes = 'html'

[[plugins]]
repository = 'nvie/vim-flake8'
filetypes = 'python'
#
[[plugins]]
repository = 'vim-ruby/vim-ruby'
filetypes = ['ruby', 'eruby']

[[plugins]]
repository = 'vim-perl/vim-perl'
filetypes = 'perl'

