# Sample:
# [[plugins]]
# repository =

# Filer
[[plugins]]
repository = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repository = 'justinmk/vim-dirvish'

# Productivities
## Syntax, Coding rule
[[plugins]]
repository = 'bronson/vim-trailing-whitespace'

[[plugins]]
repository = 'junegunn/vim-easy-align'

## Cursor
[[plugins]]
repository = 'Lokaltog/vim-easymotion'

[[plugins]]
repository = '907th/vim-auto-save'

## Input Support
[[plugins]]
repository = 'AndrewRadev/switch.vim'

[[plugins]]
repository = 'tomtom/tcomment_vim'

## Git
[[plugins]]
repository = 'tpope/vim-fugitive'

## Display
[[plugins]]
repository = 'itchyny/lightline.vim'

[[plugins]]
repository = 'w0ng/vim-hybrid'

[[plugins]]
repository = 'Yggdroot/indentLine'

# Memo
[[plugins]]
repository = 'glidenote/memolist.vim'

[[plugins]]
repository = 'vimwiki'

# Text objects (textobj)
[[plugins]]
repository = 'kana/vim-textobj-user'

[[plugins]]
repository = 'rhysd/vim-textobj-anyblock'
depends = 'vim-textobj-user'

[[plugins]]
repository = 'thinca/vim-textobj-between'
depends = 'vim-textobj-user'
